global:
  scrape_interval: 5s
# host.docker.internal will fail on linux so use the serivce-names => api-gateway:3000
scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'core-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'leaderboard-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3002']

  - job_name: 'evaluation-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3003']
